AWSTemplateFormatVersion: "2010-09-09"
Description: Deploys IAM roles and policies required for the AWS EKS Quick Start (qs-1p7nknohl)
Parameters:
  ORAFilesLocation:
    Description: Provide the S3 location of the downloaded Oracle client files, starting with the bucket name and the prefix where you uploaded them. Don't add a trailing slash.
      E.g., ibm-fncm-assets/oracle_client_files
      Refer to the deployment guide for more information on downloading the client files and obtaining the location
    Type: String
  QSS3BucketName:
    AllowedPattern: ^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$
    ConstraintDescription: 'Quick Start bucket name can include numbers, lowercase
      letters, uppercase letters, and hyphens (-). It cannot start or end with a hyphen
      (-).'
    Default: aws-quickstart
    Description: 'S3 bucket name for the Quick Start assets. This string can include
      numbers, lowercase letters, uppercase letters, and hyphens (-). It cannot start
      or end with a hyphen (-).'
    Type: String
Resources:
  BastionRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: QSBucketAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: s3:GetObject
                Resource: !Sub "arn:aws:s3:::${QSS3BucketName}/*"
              - Effect: Allow
                Action:
                  - s3:getObject
                Resource: !Sub 'arn:aws:s3:::${ORAFilesLocation}/*'
              - Effect: Allow
                Action:
                  - s3:getObject
                Resource: !Sub 'arn:aws:s3:::ibm-fncm-assets/*'                
              - Effect: Allow
                Action:
                  - logs:CreateLogStream
                  - logs:GetLogEvents
                  - logs:PutLogEvents
                  - logs:DescribeLogGroups
                  - logs:DescribeLogStreams
                  - logs:PutRetentionPolicy
                  - logs:PutMetricFilter
                  - logs:CreateLogGroup
                Resource: !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:*:*"
              - Effect: Allow
                Action:
                  - ec2:AssociateAddress
                  - ec2:DescribeAddresses
                  - eks:ListClusters
                Resource: "*"
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore'
        - 'arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy'
Outputs:
  BastionRole:
    Value: !Ref BastionRole
  BastionRoleARN:
    Value: !GetAtt BastionRole.Arn